<a href="https://colab.research.google.com/github/dhsingh0815/ML/blob/main/PCA_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install scikit-learn

In [5]:
import sklearn
print (sklearn.__version__)

1.5.2


In [6]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
data = np.array([[2.5, 2.4],
                 [0.5, 0.7],
                 [2.2, 2.9]])

In [8]:
scaler = StandardScaler()
data_std = scaler.fit_transform(data)

In [9]:
pca=PCA(n_components=2)
pca.fit(data_std)

PCA(n_components=2)

In [11]:
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[0.96829339 0.03170661]


In [12]:
eigenvectors = pca.components_
print(eigenvectors)

[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [14]:
eigenvalues=pca.explained_variance_
print(eigenvalues)

[2.90488016 0.09511984]


In [15]:
print("Standardized Data:")
print(data_std)
print("\nEigenvectors:")
print(eigenvectors)
print("\nEigenvalues:")
print(eigenvalues)
print("\nExplained Variance Ratio:")
print(explained_variance)
print("\nPrincipal Components(Projected Data):")
print(pca.transform(data_std))
print("\nCovariance Matrix:")
print(np.cov(data_std.T))


Standardized Data:
[[ 0.87056284  0.4247954 ]
 [-1.40047065 -1.38058503]
 [ 0.52990781  0.95578964]]

Eigenvectors:
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

Eigenvalues:
[2.90488016 0.09511984]

Explained Variance Ratio:
[0.96829339 0.03170661]

Principal Components(Projected Data):
[[ 0.91595659  0.31520518]
 [-1.96650334 -0.01406126]
 [ 1.05054674 -0.30114393]]

Covariance Matrix:
[[1.5        1.40488016]
 [1.40488016 1.5       ]]


What is Explained Variance Ratio:?